import "@fontsource/poppins/400.css";
import "@fontsource/poppins/700.css";
import "@fontsource/pt-sans/400.css";
import "@fontsource/pt-sans/700.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body style={{
        fontFamily: "'PT Sans', sans-serif",
        background: "#E6F0FF",
        margin: 0,
        padding: 0,
      }}>
        {children}
      </body>
    </html>
  );
} 